inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  UseCache: true
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'

Rails:
  Enabled: true

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Layout/DotPosition:
  EnforcedStyle: trailing
Style/RegexpLiteral:
  EnforcedStyle: mixed
Style/AccessModifierDeclarations:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
